### ISSUE TITLE
Switchen tussen scenarios

### ISSUE THREAD

**Issue by ngesquiere** [dwengovzw/Blockly-for-Dwenguino#102]
Gaat vlot van sociale robot naar bv. rijdende robot, maar terug naar sociale robot lukt niet meer.

**Comment by tomneutens** [comment]
Kan je een specifieke case geven want ik kan dat precies niet reproduceren. Bij mij kan ik vlot tussen alles switchen..

**Comment by ngesquiere** [comment]
![image](https://user-images.githubusercontent.com/48352335/194143114-58a9ed61-a121-415b-a597-2e802275f0ea.png)
