### ISSUE TITLE
Add warning when closing tab in Dwengo editor

### ISSUE THREAD

**Issue by BTWS2** [dwengovzw/Blockly-for-Dwenguino#116]

**Comment by tomneutens** [comment]
I think this will be annoying for the user to have to confirm each time they close a tab. Might a better option be to implement a "Reopen closed tab" feature like the ones browsers provide?

**Comment by BTWS2** [comment]
Hmm, that's true. Maybe only show a warning if changes are made to the example/boilerplate and user wants to close it? A changed tab can be indicated with a star (e.g. `*Welcome`). Scanning through examples will not cause a warning this way. Closing code with own changes should result in a warning or at least retrieve the changes. Depending on the UI, I think "Reopen closed tab" will be too complicated.
