### ISSUE TITLE
Indicate processing step with rotating gear in same place

### ISSUE THREAD

**Issue by BTWS2** [dwengovzw/Blockly-for-Dwenguino#117]
Replace the circle with the cross or play-icon with the rotating gear icon instead of replacing the robot icon .
Before:
![image](https://user-images.githubusercontent.com/56451049/197527334-0dc995fc-ecb1-4adc-b777-15daa3a1190f.png)
After suggestion:
![image](https://user-images.githubusercontent.com/56451049/197527261-dd8d8936-fb65-41ef-8a6a-ea3f6f9614ed.png)

**Comment by tomneutens** [comment]
Fixed in last commit.
