### ISSUE TITLE
Blockly translations guide

### ISSUE THREAD

**Issue by kakila** [dwengovzw/Blockly-for-Dwenguino#12]
Dear all,

I would like to contribute translations for the online dwenguino simulator (guess is the same for dwenguiiono blockly (still not working here, see issue https://github.com/dwengovzw/Blockly-for-Dwenguino/issues/10)).

Is there a guide for contributing translations?
Thanks

**Comment by fwyffels** [comment]
Thanks for your contribution. Translation(s) can be added [here](https://github.com/dwengovzw/Blockly-for-Dwenguino/tree/dwenguinoblockly-standalone/Blockly-for-Dwenguino/DwenguinoIDE/msg), the English and Dutch version are the most complete, so best to start from there.
