### ISSUE TITLE
leds (in social robot) 2

### ISSUE THREAD

**Issue by ngesquiere** [dwengovzw/Blockly-for-Dwenguino#131]
zie bijgevoegde xml.
led0 gaat niet aan in de for-lus

![image](https://user-images.githubusercontent.com/48352335/199570448-bcdfb76c-cabe-4018-bce6-0b644d476386.png)
[issueleds2.txt](https://github.com/dwengovzw/Blockly-for-Dwenguino/files/9923118/issueleds2.txt)

**Comment by tomneutens** [comment]
Bij vertaling naar tekstuele code moet het pinMode commando voor de digitalWrite komen.
