### ISSUE TITLE
(temporarily) Removing component titles

### ISSUE THREAD

**Issue by BjarneVdv** [dwengovzw/Blockly-for-Dwenguino#154]
In **Social Robot**

When components are added in the simulation window, they show extra information on top at all times. This seems to be visually impacting the user experience.

Some options to deal with this are:

- Removing the 'titles' entirely
- Hiding the 'titles' during simulation
- Providing a button to hide/unhide 'titles'

**Comment by tomneutens** [comment]
In the latest version, the titles are only shown on hover. Do you think this is acceptable?
