### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by SebCanet** [dwengovzw/Blockly-for-Dwenguino#3]
Hi,
thanks to your code I've developped a light version ([https://github.com/technologiescollege/BlocklyArduinoIDEPlugin](https://github.com/technologiescollege/BlocklyArduinoIDEPlugin)) to my software Blockly@rduino ([https://github.com/technologiescollege/Blockly-at-rduino]https://github.com/technologiescollege/Blockly-at-rduino).

Thanks a lot!

**Comment by tomneutens** [comment]
Hi Seb,

Thanks for refering to our repo! Nice to see other people use our code to
make something great!

Kind regards,
Tom

2018-03-06 17:52 GMT+01:00 SebCanet <notifications@github.com>:
