### ISSUE TITLE
Buzzer holds first tone only (simulator)

### ISSUE THREAD

**Issue by BjarneVdv** [dwengovzw/Blockly-for-Dwenguino#57]
De buzzer verandert niet van toon als er al een toon aan het spelen is. Je moet dus eerst de toon die speelt, uitzetten voor je een nieuwe toon kan starten.

Op de Dwenguino werkt dit wel als intended (nieuwe toon beëindigt automatisch oude toon).

**Comment by zimcke** [comment]
This bug has been fixed.
