### ISSUE TITLE
BUG: handjes omhoog en omlaag

### ISSUE THREAD

**Issue by ngesquiere** [dwengovzw/Blockly-for-Dwenguino#62]
Sociale robot: bij uitvoer van het blok handjes omhoog gaan ze omlaag en omgekeerd

**Comment by zimcke** [comment]
Heb je een voorbeeldprogramma (xml-bestand)? Ik krijg deze bug niet gereproduceerd door gewoon het handen-omlaag of handen-omhoogblok te gebruiken, dus ik vermoed dat ze in combinatie met andere blokken problemen geven.

**Comment by ngesquiere** [comment]
![armenbenedenuitgevoerd](https://user-images.githubusercontent.com/48352335/138669420-53cc3cc5-d2a6-4d13-98d8-322cf9af731e.png)
![armenbeneden](https://user-images.githubusercontent.com/48352335/138669436-c460675c-4bcc-4945-bc54-cc2a3ec1105b.png)

Ik heb screenshot toegevoegd. Ik gebruik enkel dat blok maar er zijn wel nog andere actuatoren/sensoren in gebruik.

**Comment by zimcke** [comment]
Dit is geen bug in de software, maar eerder een kwestie van usability. In jouw voorbeeld moet de rechterarm servo 4 worden (en dus niet servo 3) en de linkerarm is dan servo 3 (en niet servo 4). Door de oriëntatie van de servomotoren krijg je het omgekeerde effect als je de servomotoren omwisselt. De begrippen "links" en "rechts" zijn telkens zoals ze door de robot zouden worden geïnterpreteerd, want die bestuur je. Misschien kunnen we eens nadenken over hoe we dit duidelijk maken in de interface?

**Comment by ngesquiere** [comment]
OK rechts en links had ik niet op gelet. Maar de duimen moeten dus naar buiten wijzen als de handjes naar beneden zijn, zoals in het voorbeeld in het blok.
