### ISSUE TITLE
spirograaf sonar schuifbalk

### ISSUE THREAD

**Issue by ngesquiere** [dwengovzw/Blockly-for-Dwenguino#64]
Kan er een schuifbalk komen bij spirograaf, zoals bij de sociale robot, om afstand die sonar meet tijdens simulatie aan te passen?

**Comment by tomneutens** [comment]
For now, I think it is possible by changing the value in the input box.

**Comment by ngesquiere** [comment]
OK

Op ma 8 aug. 2022 om 11:24 schreef Tom ***@***.***>:
