### ISSUE TITLE
theremin

### ISSUE THREAD

**Issue by ngesquiere** [dwengovzw/Blockly-for-Dwenguino#65]
Voor project theremin gebruik je in principe twee soorten programma's:
programma's die knoppen en buzzer gebruiken en programma's die sonar en buzzer gebruiken.
De eerste soort programma's kan je maken in het scenario van de rijdende robot.
De tweede soort in het scenario van de sociale robot maar in dat scenario kan je de knoppen niet gebruiken aangezien de Dwenguino er niet getoond wordt.
Je kan theremin doen als je switcht tussen scenario's.
Als je wil gaan uitbreiden en zowel sonar als knoppen (en eventueel ook leds op de Dwenguino) wil gebruiken, dan gaat dit nu niet in de simulator, wel fysiek.
Voor de theremin is eigenlijk een scenario nodig met Dwenguino en sonar met schuifbalk.

**Comment by tomneutens** [comment]
Klopt, er moet eigenlijk een scenario komen gelijkaardig aan de sociale robot maar met enkel de dwenguino. Daarbij moeten ze ook nog extra eigen sensoren en actuatoren kunnen toevoegen.

**Comment by ngesquiere** [comment]
In eerste fase zijn sensoren voldoende. Sonar voor theremin en temperatuursensor (en eventueel enkele andere) voor bv. weerstation

**Comment by tomneutens** [comment]
Je kan in het scenario van de rijdende robot de afstand van de sensor ook aanpassen dus in principe kan je alles voor de theremin doen in het scenario van de rijdende robot?

**Comment by ngesquiere** [comment]
Je zou dat geleidelijk aan dus continu moeten kunnen doen, zoals je met je
hand dichter en verder van de sonar gaat, dus voor de theremin is wel een
schuifbalk nodig denk ik

Op ma 8 aug. 2022 om 11:27 schreef Tom ***@***.***>:
