### ISSUE TITLE
Plotter

### ISSUE THREAD

**Issue by ngesquiere** [dwengovzw/Blockly-for-Dwenguino#66]
Kan de code van de plotter teruggezet worden naar oudere versie, want nu werkt 
![coord](https://user-images.githubusercontent.com/48352335/149666208-68528537-ec2f-4268-ba2a-2e719b61d023.png)
bv. niet meer.

**Comment by tomneutens** [comment]
Er zitten nog wel bugs in het plotter scenario. Wordt dat momenteel ergens voor gebruikt? Ik zou het anders weglaten?

**Comment by ngesquiere** [comment]
Het wordt inderdaad nog niet gebruikt, hoewel het mooie toepassingen biedt voor de eerste graad om te oefenen met coördinaten in wiskunde en aardrijkskunde. Dus het mag momenteel weg.
De oude versie werkte wel of zaten daar ook nog bugs in? Het probleem daarmee was de oriëntatie van de y-as.

**Comment by tomneutens** [comment]
Zitten al altijd bugs in. Is geschreven door thesisstudent en ik heb nog nooit de tijd gehad om zijn code op te kuisen.

**Comment by tomneutens** [comment]
Plotter scenario has been removed. No material for it and buggy.
