### ISSUE TITLE
Code wordt niet uitgevoerd

### ISSUE THREAD

**Issue by ngesquiere** [dwengovzw/Blockly-for-Dwenguino#76]
![whileforsamen](https://user-images.githubusercontent.com/48352335/164965163-44377caa-a581-4e63-b10f-6dd3c1366d5a.png)

![image](https://user-images.githubusercontent.com/48352335/164965182-c1616fb7-fd95-4de1-8939-a929222027eb.png)

for-lus staat niet op nieuwe lijn; code wordt niet uitgevoerd in simulator

**Comment by tomneutens** [comment]
Klopt inderdaad dat de for loop op een nieuwe lijn moet komen. Bij mij werkt de code wel in de simulator.

**Comment by tomneutens** [comment]
Added newline after while loop. In my tests the code executes like it should in the simulator.
See test case /tests/end_to_end/newline_after_wait_for_button
