### ISSUE TITLE
tekstuele code concatenatie

### ISSUE THREAD

**Issue by ngesquiere** [dwengovzw/Blockly-for-Dwenguino#77]
![image](https://user-images.githubusercontent.com/48352335/164976863-a528c4de-48dc-4787-b8fa-3dafcddb1ca8.png)

Is het niet raar dat de code toelaat om string en int te concateneren?

Hiermee verwant: in de volgende code had ik verwacht dat de int zou omgezet worden naar een string, door de toevoeging maak tekst met, maar dat gebeurt niet. Waarom is 'maak tekst met' dan nodig en kan je niet direct het getal meegeven aan de printopdracht?
![image](https://user-images.githubusercontent.com/48352335/164977054-962e9c05-20ed-428f-91d2-e55331df5a05.png)

**Comment by tomneutens** [comment]
We moeten die blok misschien hernoemen naar "combineer tekst"?

**Comment by tomneutens** [comment]
Changed this so the block to concatenate text casts the arguments to strings. This works but sometimes results in ugly code since parameters that are already strings are cast again. f.e.:

String(String("tekst")) krijgt.
