### ISSUE TITLE
tijd in simulator bij functies

### ISSUE THREAD

**Issue by ngesquiere** [dwengovzw/Blockly-for-Dwenguino#78]
![image](https://user-images.githubusercontent.com/48352335/165041713-bf208014-011f-4279-9cc6-6723c641c585.png)

Er is hier iets mis met de timing in de simulator. De seconden zijn heel kort.

**Comment by tomneutens** [comment]
Added test program to /tests/end_to_end_tests/time_parameter_in_function/sample.xml

**Comment by tomneutens** [comment]
There was an issue with the way the sleep parameter was extracted from the code. It was always seen as a literal. Consequently, when a parameter value was added, the delay function did not work. Now the parameter of the delay function is always evaluated using the current virtual machine state yielding the correct value.
