### ISSUE TITLE
Schuifbalk

### ISSUE THREAD

**Issue by ngesquiere** [dwengovzw/Blockly-for-Dwenguino#95]
![image](https://user-images.githubusercontent.com/48352335/184547333-6e9cb6e2-0c22-47a5-adf9-994846ab6b65.png)

Als je de schuifbalk wilt gebruiken, dan verschuiven de ledmatrices en de schuifbalk doet niets.

**Comment by tomneutens** [comment]
Ik denk dat dit is omdat het formaat van de led matrices verkeerd was waardoor de component groter is dan de afbeelding. Zou aangepast moeten zijn in laatste commit.
