### ISSUE TITLE
overschakelen naar andere taal doet programma verdwijnen

### ISSUE THREAD

**Issue by ngesquiere** [dwengovzw/Blockly-for-Dwenguino#97]
Vroeger kon je een programma in de Nederlandstalige blokken maken en dan de taal wijzigen naar Frans en dan verschenen alle blokken in het Frans.
Nu verdwijnt het programma

**Comment by tomneutens** [comment]
Is dat in andere talen ook een probleem?

Op vr 19 aug. 2022 21:11 schreef ngesquiere ***@***.***>:
