### ISSUE TITLE
werkt soms en soms niet

### ISSUE THREAD

**Issue by ngesquiere** [dwengovzw/Blockly-for-Dwenguino#99]
![image](https://user-images.githubusercontent.com/48352335/187139303-b0088c0b-9643-42e0-9c33-c9dac8b5e2db.png)

Als ik bv. afstand sonar op 117 simuleer begint hij soms wel te zwaaien hoewel dat niet mag. Maar raar want soms werkt de simulatie wel goed, Bij 104 heb ik hetzelfde. Bij 144 werkt het precies wel altijd goed.

**Comment by tomneutens** [comment]
Slider value needs to be set to zero on simulation restart.
